### ISSUE TITLE
KSQL not connecting to schema registry

### ISSUE THREAD

**Issue by tjaard123** [synthesis-labs/polaris#13]
It seems like our KSQL server inside the confluent kafka platform included in polaris isn't able to connect to the schema registry.

I've tried editing the chart to include reference to schema registry but doesn't do the trick.  When you port-forward the ksql server and try creating an avro stream the error is connection refused.

[cp-ksql-server/values.yaml](https://github.com/synthesis-labs/polaris/blob/master/charts/polaris-kafka/charts/cp-helm-charts/charts/cp-ksql-server/values.yaml)

```yaml
## e.g. gnoble-panther-cp-schema-registry:8081
cp-schema-registry:
  url: ""
```
